/**
 * Copy the normative specification in, rather than transcribing it.
 *
 * `placepin-spec/SPEC.md` is the single source of truth. This site renders it;
 * it does not own it. A second hand-maintained copy would drift, and a drifted
 * spec is worse than no spec — §10 is explicit that changing what a code means
 * requires a visible version change, and a doc site quietly diverging is
 * exactly the invisible kind.
 *
 * The output is gitignored and regenerated by `dev` and `build`, so there is
 * nothing to forget to re-run.
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SPEC_REPO = resolve(here, '../../placepin-spec');
const OUT = resolve(here, '../docs/spec/spec.md');

const source = resolve(SPEC_REPO, 'SPEC.md');
if (!existsSync(source)) {
  console.error(
    `\n  Cannot find ${source}\n\n` +
      `  about.placepin.org renders the specification from the sibling\n` +
      `  placepin-spec checkout. Clone it next to this repo:\n\n` +
      `    git clone https://github.com/placepin-org/placepin-spec\n`,
  );
  process.exit(1);
}

const spec = readFileSync(source, 'utf8');

/**
 * The spec opens with its own H1 and a subtitle line. VitePress wants
 * frontmatter for the page title and description, and its outline is built
 * from H2/H3 — both of which the document already has, so nothing is rewritten
 * beyond the header being prepended.
 */
const frontmatter = [
  '---',
  'title: Specification',
  'description: The normative placepin location protocol specification, v5 draft.',
  'editLink: false',
  'outline: [2, 3]',
  '---',
  '',
  '<!--',
  '  GENERATED FILE — do not edit.',
  '  Synced verbatim from placepin-spec/SPEC.md by scripts/sync-spec.mjs.',
  '  Change the spec in that repo; this is only the rendering of it.',
  '-->',
  '',
  // Stated on the page, not just in a comment a reader never sees. Somebody
  // arriving here to propose a change should be pointed at the document that
  // actually governs, rather than at a rendering of it.
  '::: info The normative document',
  'This page is [`SPEC.md`](https://github.com/placepin-org/placepin-spec/blob/main/SPEC.md)',
  'from `placepin-spec`, rendered verbatim. Conformance is defined by the',
  '[conformance vectors](https://github.com/placepin-org/placepin-spec/blob/main/vectors.json),',
  'not by this prose — see §03. Proposals belong in that repo.',
  ':::',
  '',
].join('\n');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, frontmatter + spec, 'utf8');

const lines = spec.split('\n').length;
console.log(`  synced SPEC.md → docs/spec/spec.md (${lines} lines)`);

/**
 * Verify every deep link into the spec still lands.
 *
 * The nav, the sidebar and the home page all point at anchors inside a
 * document this repo does not own. VitePress's dead-link check validates that
 * the *page* exists and stops there, so a renamed heading upstream breaks a
 * dozen links silently and the build stays green. That is exactly the failure
 * this project cannot afford twice, so it fails here instead.
 *
 * The slug rule mirrors VitePress's (`@mdit-vue/shared`'s `slugify`): lowercase,
 * strip the characters it strips, spaces to hyphens, and a leading digit gets
 * an underscore prefix — which is why the anchors read `_03-·-the-grid`.
 */
/** Pages written here, as opposed to the one synced in. Both checks below
 *  walk this list, so a new page joins them by being added once. */
const AUTHORED_PAGES = ['../docs/index.md', '../docs/next.md', '../docs/why.md'];

const slugify = (heading) =>
  heading
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[!"#$%&'()*+,./:;<=>?@[\]^`{|}~]/g, '')
    .replace(/\s+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/^(\d)/, '_$1')
    .toLowerCase();

const available = new Set(
  spec
    .split('\n')
    // Fenced code can contain lines starting with '#'. Only real headings count.
    .filter((line, i, all) => /^#{1,4} /.test(line) && !inFence(all, i))
    .map((line) => slugify(line.replace(/^#+\s+/, ''))),
);

function inFence(lines, upto) {
  let open = false;
  for (let i = 0; i < upto; i++) if (/^```/.test(lines[i])) open = !open;
  return open;
}

const referenced = [];
for (const file of AUTHORED_PAGES.concat('../docs/.vitepress/config.ts')) {
  const text = readFileSync(resolve(here, file), 'utf8');
  for (const [, anchor] of text.matchAll(/\/spec\/spec#([^)'"\s]+)/g)) {
    referenced.push({ file, anchor: decodeURIComponent(anchor) });
  }
}

const broken = referenced.filter(({ anchor }) => !available.has(anchor));
if (broken.length) {
  console.error(`\n  ${broken.length} link(s) point at headings SPEC.md no longer has:\n`);
  for (const { file, anchor } of broken) console.error(`    #${anchor}  (${file})`);
  console.error(
    `\n  The specification lives in placepin-spec and was changed there.\n` +
      `  Update the links to match, rather than the other way round.\n`,
  );
  process.exit(1);
}

console.log(`  verified ${referenced.length} deep links into the spec`);

/**
 * `breaks: true` makes a wrapped line a rendering bug.
 *
 * The setting exists for SPEC.md, whose line breaks are meaningful. The cost is
 * that a hard-wrapped paragraph in an authored page becomes a stack of <br>s —
 * which looks like a deliberate stanza and is nothing of the kind. It is an
 * easy mistake to make and an easy one to miss, because the words are all still
 * there and only the rag looks odd.
 *
 * So: authored prose is written unwrapped, and that is checked rather than
 * remembered.
 */
const wrapped = [];

for (const file of AUTHORED_PAGES) {
  const lines = readFileSync(resolve(here, file), 'utf8').split('\n');
  let inFrontmatter = lines[0]?.trim() === '---';
  let inFence = false;
  let inComponent = false;

  lines.forEach((line, i) => {
    if (inFrontmatter) {
      if (i > 0 && line.trim() === '---') inFrontmatter = false;
      return;
    }
    if (line.startsWith('```')) return void (inFence = !inFence);
    if (inFence) return;
    // Multi-line component props are JavaScript, not prose.
    if (/^<[A-Z]/.test(line)) inComponent = !/\/>\s*$/.test(line);
    if (inComponent) return void (inComponent = !/^\]?"?\s*\/>\s*$/.test(line));

    const next = lines[i + 1] ?? '';
    const isProse = line.trim() && !/^([#>|<:]|```)/.test(line.trim());
    const continues = next.trim() && !/^([#>|<:\s]|[-*+] |\d+\. |```)/.test(next);
    if (isProse && continues) wrapped.push({ file, line: i + 1, text: line.trim() });
  });
}

if (wrapped.length) {
  console.error(`\n  ${wrapped.length} hard-wrapped prose line(s). markdown \`breaks\` is on,`);
  console.error(`  so each of these renders a <br> mid-sentence:\n`);
  for (const { file, line, text } of wrapped) {
    console.error(`    ${file}:${line}  ${text.slice(0, 60)}…`);
  }
  console.error(`\n  Join each paragraph onto one line.\n`);
  process.exit(1);
}
